export type Role = "Admin" | "Quality Lead" | "Inspector";
export type Status = "Active" | "Inactive";

export const DEPARTMENTS = [
  "Engineering",
  "Product",
  "Design",
  "Sales",
  "Marketing",
  "HR",
  "Finance",
  "Operations",
  "Support",
] as const;

export type Department = (typeof DEPARTMENTS)[number];

export const ROLES: Role[] = ["Admin", "Quality Lead", "Inspector"];

export type User = {
  id: string;
  name: string;
  email: string;
  role: Role;
  department: Department;
  status: Status;
  lastActive: string; // ISO
  createdAt: string; // ISO
};

const daysAgo = (n: number) => new Date(Date.now() - n * 24 * 60 * 60 * 1000).toISOString();
const minutesAgo = (n: number) => new Date(Date.now() - n * 60 * 1000).toISOString();

export const MOCK_USERS: User[] = [
  {
    id: "u_01",
    name: "Amelia Chen",
    email: "amelia.chen@pms.com",
    role: "Admin",
    department: "Engineering",
    status: "Active",
    lastActive: minutesAgo(4),
    createdAt: daysAgo(420),
  },
  {
    id: "u_02",
    name: "Noah Patel",
    email: "noah.patel@pms.com",
    role: "Quality Lead",
    department: "Product",
    status: "Active",
    lastActive: minutesAgo(38),
    createdAt: daysAgo(390),
  },
  {
    id: "u_03",
    name: "Sofia Rivera",
    email: "sofia.rivera@pms.com",
    role: "Inspector",
    department: "Design",
    status: "Active",
    lastActive: minutesAgo(120),
    createdAt: daysAgo(310),
  },
  {
    id: "u_04",
    name: "Liam Becker",
    email: "liam.becker@pms.com",
    role: "Quality Lead",
    department: "Sales",
    status: "Active",
    lastActive: minutesAgo(15),
    createdAt: daysAgo(280),
  },
  {
    id: "u_05",
    name: "Olivia Park",
    email: "olivia.park@pms.com",
    role: "Inspector",
    department: "Marketing",
    status: "Inactive",
    lastActive: daysAgo(48),
    createdAt: daysAgo(260),
  },
  {
    id: "u_06",
    name: "Ethan Brooks",
    email: "ethan.brooks@pms.com",
    role: "Inspector",
    department: "Engineering",
    status: "Active",
    lastActive: minutesAgo(7),
    createdAt: daysAgo(240),
  },
  {
    id: "u_07",
    name: "Mia Tanaka",
    email: "mia.tanaka@pms.com",
    role: "Admin",
    department: "Operations",
    status: "Active",
    lastActive: minutesAgo(2),
    createdAt: daysAgo(210),
  },
  {
    id: "u_08",
    name: "Daniel Okafor",
    email: "daniel.okafor@pms.com",
    role: "Quality Lead",
    department: "Finance",
    status: "Active",
    lastActive: minutesAgo(180),
    createdAt: daysAgo(190),
  },
  {
    id: "u_09",
    name: "Isabella Romano",
    email: "isabella.romano@pms.com",
    role: "Inspector",
    department: "HR",
    status: "Active",
    lastActive: minutesAgo(60),
    createdAt: daysAgo(170),
  },
  {
    id: "u_10",
    name: "James Sullivan",
    email: "james.sullivan@pms.com",
    role: "Inspector",
    department: "Support",
    status: "Inactive",
    lastActive: daysAgo(14),
    createdAt: daysAgo(150),
  },
  {
    id: "u_11",
    name: "Ava Lindqvist",
    email: "ava.lindqvist@pms.com",
    role: "Quality Lead",
    department: "Engineering",
    status: "Active",
    lastActive: minutesAgo(22),
    createdAt: daysAgo(140),
  },
  {
    id: "u_12",
    name: "Lucas Moreau",
    email: "lucas.moreau@pms.com",
    role: "Inspector",
    department: "Product",
    status: "Active",
    lastActive: minutesAgo(95),
    createdAt: daysAgo(130),
  },
  {
    id: "u_13",
    name: "Harper Nguyen",
    email: "harper.nguyen@pms.com",
    role: "Inspector",
    department: "Design",
    status: "Active",
    lastActive: minutesAgo(310),
    createdAt: daysAgo(110),
  },
  {
    id: "u_14",
    name: "Benjamin Cole",
    email: "benjamin.cole@pms.com",
    role: "Quality Lead",
    department: "Marketing",
    status: "Active",
    lastActive: minutesAgo(45),
    createdAt: daysAgo(95),
  },
  {
    id: "u_15",
    name: "Charlotte Reyes",
    email: "charlotte.reyes@pms.com",
    role: "Inspector",
    department: "Sales",
    status: "Active",
    lastActive: minutesAgo(11),
    createdAt: daysAgo(80),
  },
  {
    id: "u_16",
    name: "Henry Wallace",
    email: "henry.wallace@pms.com",
    role: "Inspector",
    department: "Engineering",
    status: "Inactive",
    lastActive: daysAgo(21),
    createdAt: daysAgo(75),
  },
  {
    id: "u_17",
    name: "Evelyn Schmidt",
    email: "evelyn.schmidt@pms.com",
    role: "Admin",
    department: "HR",
    status: "Active",
    lastActive: minutesAgo(70),
    createdAt: daysAgo(60),
  },
  {
    id: "u_18",
    name: "Mason Hughes",
    email: "mason.hughes@pms.com",
    role: "Inspector",
    department: "Operations",
    status: "Active",
    lastActive: minutesAgo(140),
    createdAt: daysAgo(45),
  },
  {
    id: "u_19",
    name: "Aria Khalil",
    email: "aria.khalil@pms.com",
    role: "Inspector",
    department: "Finance",
    status: "Active",
    lastActive: minutesAgo(28),
    createdAt: daysAgo(34),
  },
  {
    id: "u_20",
    name: "Logan Pierce",
    email: "logan.pierce@pms.com",
    role: "Quality Lead",
    department: "Support",
    status: "Active",
    lastActive: minutesAgo(18),
    createdAt: daysAgo(26),
  },
  {
    id: "u_21",
    name: "Scarlett Adeyemi",
    email: "scarlett.adeyemi@pms.com",
    role: "Inspector",
    department: "Product",
    status: "Active",
    lastActive: minutesAgo(6),
    createdAt: daysAgo(19),
  },
  {
    id: "u_22",
    name: "Jack Morrison",
    email: "jack.morrison@pms.com",
    role: "Inspector",
    department: "Engineering",
    status: "Active",
    lastActive: minutesAgo(50),
    createdAt: daysAgo(12),
  },
  {
    id: "u_23",
    name: "Penelope Stone",
    email: "penelope.stone@pms.com",
    role: "Inspector",
    department: "Design",
    status: "Inactive",
    lastActive: daysAgo(9),
    createdAt: daysAgo(8),
  },
  {
    id: "u_24",
    name: "Wyatt Garcia",
    email: "wyatt.garcia@pms.com",
    role: "Inspector",
    department: "Sales",
    status: "Active",
    lastActive: minutesAgo(3),
    createdAt: daysAgo(3),
  },
];
