/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnauthorizedRouteImport } from './routes/unauthorized'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AccessRestrictedRouteImport } from './routes/access-restricted'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppUsersRouteImport } from './routes/_app.users'
import { Route as AppQualityLeadRouteImport } from './routes/_app.quality-lead'
import { Route as AppInspectorRouteImport } from './routes/_app.inspector'
import { Route as AppDashboardRouteImport } from './routes/_app.dashboard'

const UnauthorizedRoute = UnauthorizedRouteImport.update({
  id: '/unauthorized',
  path: '/unauthorized',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessRestrictedRoute = AccessRestrictedRouteImport.update({
  id: '/access-restricted',
  path: '/access-restricted',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppUsersRoute = AppUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AppRoute,
} as any)
const AppQualityLeadRoute = AppQualityLeadRouteImport.update({
  id: '/quality-lead',
  path: '/quality-lead',
  getParentRoute: () => AppRoute,
} as any)
const AppInspectorRoute = AppInspectorRouteImport.update({
  id: '/inspector',
  path: '/inspector',
  getParentRoute: () => AppRoute,
} as any)
const AppDashboardRoute = AppDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/access-restricted': typeof AccessRestrictedRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof AppDashboardRoute
  '/inspector': typeof AppInspectorRoute
  '/quality-lead': typeof AppQualityLeadRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/access-restricted': typeof AccessRestrictedRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/dashboard': typeof AppDashboardRoute
  '/inspector': typeof AppInspectorRoute
  '/quality-lead': typeof AppQualityLeadRoute
  '/users': typeof AppUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/access-restricted': typeof AccessRestrictedRoute
  '/login': typeof LoginRoute
  '/unauthorized': typeof UnauthorizedRoute
  '/_app/dashboard': typeof AppDashboardRoute
  '/_app/inspector': typeof AppInspectorRoute
  '/_app/quality-lead': typeof AppQualityLeadRoute
  '/_app/users': typeof AppUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/access-restricted'
    | '/login'
    | '/unauthorized'
    | '/dashboard'
    | '/inspector'
    | '/quality-lead'
    | '/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/access-restricted'
    | '/login'
    | '/unauthorized'
    | '/dashboard'
    | '/inspector'
    | '/quality-lead'
    | '/users'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/access-restricted'
    | '/login'
    | '/unauthorized'
    | '/_app/dashboard'
    | '/_app/inspector'
    | '/_app/quality-lead'
    | '/_app/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  AccessRestrictedRoute: typeof AccessRestrictedRoute
  LoginRoute: typeof LoginRoute
  UnauthorizedRoute: typeof UnauthorizedRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unauthorized': {
      id: '/unauthorized'
      path: '/unauthorized'
      fullPath: '/unauthorized'
      preLoaderRoute: typeof UnauthorizedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/access-restricted': {
      id: '/access-restricted'
      path: '/access-restricted'
      fullPath: '/access-restricted'
      preLoaderRoute: typeof AccessRestrictedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/users': {
      id: '/_app/users'
      path: '/users'
      fullPath: '/users'
      preLoaderRoute: typeof AppUsersRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/quality-lead': {
      id: '/_app/quality-lead'
      path: '/quality-lead'
      fullPath: '/quality-lead'
      preLoaderRoute: typeof AppQualityLeadRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/inspector': {
      id: '/_app/inspector'
      path: '/inspector'
      fullPath: '/inspector'
      preLoaderRoute: typeof AppInspectorRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/dashboard': {
      id: '/_app/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AppDashboardRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppDashboardRoute: typeof AppDashboardRoute
  AppInspectorRoute: typeof AppInspectorRoute
  AppQualityLeadRoute: typeof AppQualityLeadRoute
  AppUsersRoute: typeof AppUsersRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppDashboardRoute: AppDashboardRoute,
  AppInspectorRoute: AppInspectorRoute,
  AppQualityLeadRoute: AppQualityLeadRoute,
  AppUsersRoute: AppUsersRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  AccessRestrictedRoute: AccessRestrictedRoute,
  LoginRoute: LoginRoute,
  UnauthorizedRoute: UnauthorizedRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
